module.exports = {
  DB_CONNECTION_STRING: process.env.DB_CONNECTION_STRING,
  SESSION_SECRET: process.env.SESSION_SECRET,
  EMAIL_LOGIN: process.env.EMAIL_LOGIN,
  EMAIL_PASSWORD: process.env.EMAIL_PASSWORD,
  PAY_LOGIN: process.env.PAY_LOGIN,
  PAY_PASSWORD: process.env.PAY_PASSWORD
}